# Generated by Django 4.2.6 on 2023-11-06 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_osoba_stanowisko_delete_person_delete_team_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'verbose_name_plural': 'Osoby'},
        ),
        migrations.AlterModelOptions(
            name='stanowisko',
            options={'verbose_name_plural': 'Stanowiska'},
        ),
        migrations.AlterField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
