# Generated by Django 4.2.6 on 2023-11-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0005_alter_osoba_data_dodania'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='data_dodania',
        ),
    ]
